### ISSUE TITLE
Can't start with or without libelperiodic

### ISSUE THREAD

**Issue by denser** [sippy/b2bua#31]
Hi, i get README and have Debian 9 OS. 

Try to start `b2bua_simple -f -n 10.125.184.2` but have error about missing module
```Traceback (most recent call last):
  File "/usr/local/bin/b2bua_simple", line 11, in <module>
    load_entry_point('sippy==1.1.dev0', 'console_scripts', 'b2bua_simple')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sippy/b2bua_simple.py", line 29, in <module>
    from sippy.UA import UA
  File "/usr/local/lib/python2.7/dist-packages/sippy/UA.py", line 29, in <module>
    from sippy.UasStateIdle import UasStateIdle
  File "/usr/local/lib/python2.7/dist-packages/sippy/UasStateIdle.py", line 27, in <module>
    from sippy.Time.Timeout import TimeoutAbsMono
  File "/usr/local/lib/python2.7/dist-packages/sippy/Time/Timeout.py", line 32, in <module>
    from sippy.Core.EventDispatcher import ED2
  File "/usr/local/lib/python2.7/dist-packages/sippy/Core/EventDispatcher.py", line 41, in <module>
    from elperiodic.ElPeriodic import ElPeriodic
```

Then i install via pip this module from https://github.com/sobomax/libelperiodic but get error again about so file
```Traceback (most recent call last):
  File "/usr/local/bin/b2bua_simple", line 11, in <module>
    load_entry_point('sippy==1.1.dev0', 'console_scripts', 'b2bua_simple')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sippy/b2bua_simple.py", line 29, in <module>
    from sippy.UA import UA
  File "/usr/local/lib/python2.7/dist-packages/sippy/UA.py", line 29, in <module>
    from sippy.UasStateIdle import UasStateIdle
  File "/usr/local/lib/python2.7/dist-packages/sippy/UasStateIdle.py", line 27, in <module>
    from sippy.Time.Timeout import TimeoutAbsMono
  File "/usr/local/lib/python2.7/dist-packages/sippy/Time/Timeout.py", line 32, in <module>
    from sippy.Core.EventDispatcher import ED2
  File "/usr/local/lib/python2.7/dist-packages/sippy/Core/EventDispatcher.py", line 41, in <module>
    from elperiodic.ElPeriodic import ElPeriodic
  File "/usr/local/lib/python2.7/dist-packages/elperiodic/ElPeriodic.py", line 36, in <module>
    _elpl = cdll.LoadLibrary('libelperiodic.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libelperiodic.so: cannot open shared object file: No such file or directory
```

I cant make or else with it and cant find any info why it wont work how it looks in README on Debian 9. 
Pls help me?

**Comment by sergani** [comment]
Hi Denser, I'm wondering if you were able to solve this issue. I'm stuck at the same place, even installation of libelperiodic fails due to make issues. I'm using macos. I'm wondering if you've had any luck getting b2bua to work.

**Comment by denser** [comment]
Nope, i withdraw b2bua and now focused on another direction.

**Comment by lancedouglas1** [comment]
For ElPeriodic you have to both install the python module as well as make the library and install it.
i.e.
> [\~]\$`git clone https://github.com/sobomax/libelperiodic.git && cd libelperiodic/ && ./configure && make && sudo make install && sudo ldconfig && export LD_LIBRARY_PATH=/usr/local/lib`
> [\~]\$`sudo pip3 install git+https://github.com/sobomax/libelperiodic`

Here is my **one-liner clean-install shell script** that gets my development environment up and running on RHEL8:

> [\~]\$`sudo yum update -y && sudo yum upgrade -y && sudo yum install vim git @development -y && git clone https://github.com/sobomax/libelperiodic.git && cd libelperiodic/ && ./configure && make && sudo make install && cd ~ && sudo ldconfig && export LD_LIBRARY_PATH=/usr/local/lib && sudo yum install python3 python2 python3-devel python2-devel -y && sudo pip3 install git+https://github.com/sobomax/libelperiodic && git clone https://github.com/sippy/b2bua.git && sudo pip3 install b2bua/ && b2bua_simple -f -n 127.0.0.1`

A successful run of that scripts leaves you with the simple test running and a console output of
> ('127.0.0.1', 5060)

**Comment by YyItRoad** [comment]
I can't run on my Mac.

**Comment by denser** [comment]
Cant solve my prod needs with it, so using blox sbc. Closed.
